# Generated by Django 4.2.2 on 2023-06-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('cat', models.IntegerField(choices=[(1, 'furniture'), (2, 'Kichen and Dining'), (3, 'Wall Decor')], verbose_name='category')),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('pimage', models.ImageField(upload_to='image')),
            ],
        ),
    ]
